### PR TITLE
Add syntax

### PR DESCRIPTION
**Pull request by albinahlback**
I'm basically just taking the raw markdown files (like from [this site](https://docs.julialang.org/en/v1/base/base/)) and converting them to `syntax match` by their respective title on the site.

**Currently only support for the syntax, so no actual implemention in this PR**

I am also **not** adding symbols, but everything else should be included.

Edit: These may not be exactly what you want, and might not work out of the box. But it's a start.

### CODE REVIEW

**Comment by albinahlback** [comment]
Essentials are done.

**Comment by albinahlback** [comment]
Collections and Data Structures are done.

**Comment by albinahlback** [comment]
Mathematics done.

**Comment by albinahlback** [comment]
Numbers done.

**Comment by carlobaldassi** [comment]
I don't see what's the idea here? As is, this doesn't distinguish functions, types, modules, constants, macros... Also, all of it would need to be included in the juliaExpressions cluster.
Everything but the functions should be highlighted already.
The only language that I know of in which built-in functions are highlighted in vim is Python, and there are a couple of dozens at the most (they don't include any of the built-in modules' functions), and those functions have a special status in that language, contrary to Julia's.
Also maintaining this looks like a full-time job.

**Comment by albinahlback** [comment]
Okay, think I misinterpreted the situation.

**Pull request closed without merging**
