### PR TITLE
add jmd (julia markdown) support

### PR DESCRIPTION
**Pull request by cmcaine**

### CODE REVIEW

**Comment by carlobaldassi** [comment]
Thanks, I'll review as soon as I can. I have a few questions in the meanwhile.

I'm unfamiliar with .jmd files. Are they specific to Weave.jl? If so, it would be perhaps nice to mention it somewhere (both in the PR and inside the file).

Is the syntax usable to highlight docstrings within .jl files as well? I'm not asking to do it right away, only if the rules are same.

Would this close #182? If not, what would be missing?

**Comment by cmcaine** [comment]
Thanks :)

> I'm unfamiliar with .jmd files. Are they specific to Weave.jl? If so, it would be perhaps nice to mention it somewhere (both in the PR and inside the file).

To my knowledge, yes. And sure, I'll mention it in the commit message and syntax file.

> Is the syntax usable to highlight docstrings within .jl files as well? I'm not asking to do it right away, only if the rules are same.

This file won't do this. You can take a similar approach, but you'd probably want to change the colours to be more muted for the markdown bit, no?

> close #182

I think this closes #182 and I say so in the commit message.

**Comment by cmcaine** [comment]
It's worth noting that indent support, text objects and help don't work yet.

Text objects and help would be easy to add. Indent support is a bit trickier (I think emacs is better at composing modes ;))

**Comment by rafaqz** [comment]
Any chance this will get merged?

**Comment by cmcaine** [comment]
@carlobaldassi any chance you could merge this? lmk if you'd like any more changes.

**Comment by carlobaldassi** [comment]
Superseded by #237

**Pull request closed without merging**
