### PR TITLE
Add some new 0.7 definitions

### PR DESCRIPTION
**Pull request by ararslan**

### CODE REVIEW

**Comment by ararslan** [comment]
Bump @carlobaldassi

**Comment by carlobaldassi** [comment]
It looks like I no longer have write access to this repository, for some reason, although I'm still listed as a member of the organization. Pinging some owners at random @StefanKarpinski @JeffBezanson @ViralBShah @davidanthoff @oxinabox.

**Comment by ViralBShah** [comment]
@carlobaldassi You are now an owner. I guess that teams and repos are not set up which is why you perhaps didn't have write access.

**Comment by carlobaldassi** [comment]
@ViralBShah Thanks a lot!

**Pull request merged**
